version: '2'

services:
  elasticsearch:
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  logstash:
    environment:
      LOGSTASH_CONFIG_PATH:
    volumes:
      - ${LOGSTASH_CONFIG_PATH}:/etc/logstash/conf.d/logstash.conf

volumes:
  elasticsearch:
    external: true
