version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: elasticsearch1
    environment:
      - cluster.name=rdm-elasticsearch
      - bootstrap.memory_lock
      - xpack.security.enabled=false
    logging:
      options:
       max-size: "40m"
       max-file: "5"
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
      - ./esbackup1:/usr/share/elasticsearch/backup
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - rdm-network
  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.0
    container_name: logstash1
    logging:
      options:
       max-size: "20m"
       max-file: "2"
    restart: unless-stopped
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
    volumes:
      - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
    links:
      - elasticsearch
    networks:
      - rdm-network
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: kibana1
    environment:
      - xpack.security.enabled=false
    logging:
      options:
       max-size: "20m"
       max-file: "2"
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    links:
      - elasticsearch
    networks:
      - rdm-network
networks:
  rdm-network:
    external: true